[[questions]]
id = "01-02-move-adoption"
type = "MultipleChoice"
prompt.prompt = """
All of the following networks support some form of the Move language EXCEPT:
"""
answer.answer = "Dogecoin"
prompt.distractors = [
  "Movement",
  "Aptos",
  "Sui"
]
context = """
If you have heard of Dogecoin supporting Move, please let us know so we can update this quiz!
"""