[[questions]]
id = "01-01-features-of-move"
type = "MultipleChoice"
prompt.prompt = """
Which of the following is NOT a feature of Move?
"""
answer.answer = "Closed-source, not community-driven"
prompt.distractors = [
  "Resources concept",
  "Move Prover",
  "Complated into BCS Bytecode"
]
context = """
Move language is open source, and so are all popular versions.
"""