[[questions]]
id = "02-01-type-linearity"
type = "MultipleChoice"
prompt.prompt = """
How does type linearity ensure resource safety?
"""
answer.answer = "By ensuring each resource has only one owner at a time, preventing accidental duplication or loss."
prompt.distractors = [
  "By making sure that all the fields of the struct contain linear functions.",
  "If you can ensure that each type is aligned in terms of the number of fields they have, then you can prevent unsafe code.",
  "You can ensure resource safety by adding the copy and drop abilities. Then it won't matter if they are duplicated or lost."
]
context = """
Type linearity for resources means ownership of resources is in a line, with one owner of a resource after another.  
"""