[[questions]]
id = "02-01-unsafe-access"
type = "MultipleChoice"
prompt.prompt = """
Explain why the access of `value` is unsafe?
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void printAndFree(char* data) {
    printf("Data: %s\n", data);
    free(data); // Function takes ownership and frees the memory
}

int main() {
    char* value = (char*)malloc(strlen("Hello") + 1);
    strcpy(value, "Hello");
    
    printAndFree(value); // Pass ownership of 'value' to the function

    // Attempt to access the value after it has been freed
    printf("Data after freeing: %s\n", value); // Unsafe access!

    return 0;
}
```
"""
answer.answer = "Accessing data after it has been freed can lead to undefined behavior, such as crashes or security vulnerabilities."
prompt.distractors = [
  "Accessing data after it has been freed can lead to network slowdowns and halt the blockchain due to infinite loops.",
  "Because of the line `#include <string.h>`, the line containing `printf` will not execute.",
  "The program will not compile, because accessing data after it has been freed is inherently unsafe"
]
context = """
This C program will compile despite the unsafe access of `value`. Accessing freed memory results in a "use-after-free" vulnerability, which can lead to undefined behavior, crashes, or security exploits.
"""