[[questions]]
id = "02-01-type-linearity"
type = "MultipleChoice"
prompt.prompt = """
How does type linearity ensure resource safety?
"""
answer.answer = "Accessing data after it has been freed can lead to undefined behavior, such as crashes or security vulnerabilities."
prompt.distractors = [
  "Accessing data after it has been freed can lead to network slowdowns and halt the blockchain due to infinite loops.",
  "Because of the line `#include <string.h>`, the line containing `printf` will not execute.",
  "The program will not compile, because accessing data after it has been freed is inherently unsafe"
]
context = """
This C program will compile despite the unsafe access of `value`. Accessing freed memory results in a "use-after-free" vulnerability, which can lead to undefined behavior, crashes, or security exploits.
"""