name: CI

on:
  push:
    branches:
      - '**'

env:
  RUST_LIB_BACKTRACE: 1
  RAYON_NUM_THREADS: 1
  MDBOOK_QUIZ_VERSION: 0.3.3
  AQUASCOPE_VERSION: 0.3.1
  AQUASCOPE_TOOLCHAIN: nightly-2023-08-25

jobs:
  placeholder-job:
    name: Placeholder Job
    runs-on: ubuntu-latest
    steps:
      - name: Echo a Message
        run: echo "This is a placeholder job to prevent 'No jobs were run' error."


# name: CI
# on:
#   push:
#     branches:
#       - '**'
# 
# # TODO: make a version that runs on pull_request
# 
# env:
#   RUST_LIB_BACKTRACE: 1
#   RAYON_NUM_THREADS: 1
#   MDBOOK_QUIZ_VERSION: 0.3.3
#   AQUASCOPE_VERSION: 0.3.1
#   AQUASCOPE_TOOLCHAIN: nightly-2023-08-25
# 
# jobs:
#   test:
#     name: Run tests
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
# 
#     - uses: actions/setup-node@v3
#       with:
#         node-version: 16
# 
#     - uses: pnpm/action-setup@v2
#       with:
#         version: 6.7.0
# 
#     - name: Update rustup
#       run: rustup self update
# 
#     - name: Install Rust
#       run: |
#         rustup set profile minimal
#         rustup toolchain install 1.70 -c rust-docs
#         rustup default 1.70
# 
#     - name: Install Depot
#       run: curl https://raw.githubusercontent.com/cognitive-engineering-lab/depot/main/scripts/install.sh | sh
# 
#     - name: Install Aquascope toolchain
#       run: |
#         rustup toolchain install ${AQUASCOPE_TOOLCHAIN} -c rust-src rustc-dev llvm-tools-preview miri
#         cargo +${AQUASCOPE_TOOLCHAIN} miri setup
#         echo "LD_LIBRARY_PATH=$($(rustup which --toolchain ${AQUASCOPE_TOOLCHAIN} rustc) --print target-libdir)" >> ${GITHUB_ENV}
#     
#     - name: Install binaries
#       run: |
#         mkdir bin
#         curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.25/mdbook-v0.4.25-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
#         curl -sSL https://github.com/cognitive-engineering-lab/mdbook-quiz/releases/download/v${MDBOOK_QUIZ_VERSION}/mdbook-quiz_x86_64-unknown-linux-gnu_full.tar.gz | tar -xz --directory=bin
#         curl -sSL https://github.com/cognitive-engineering-lab/aquascope/releases/download/v${AQUASCOPE_VERSION}/aquascope-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
#         echo "$(pwd)/bin" >> ${GITHUB_PATH}
# 
#     - name: Report versions
#       run: |
#         rustup --version
#         rustc -Vv
#         mdbook --version
#         mdbook-quiz --version
#         mdbook-aquascope --version
# 
#     - name: Install js-extensions
#       run: |
#         cd js-extensions
#         pnpm init-repo
# 
#     - name: Run mdbook tests
#       run: mdbook test
#     
#     - name: Build mdbook
#       run: mdbook build
# 
#     - name: Deploy to Github Pages
#       if: ${{ github.ref == 'refs/heads/main' }}
#       uses: peaceiris/actions-gh-pages@v3
#       with:
#         github_token: ${{ secrets.GITHUB_TOKEN }}
#         publish_dir: ./book
#         cname: rust-book.cs.brown.edu
# 